# Generated by Django 4.1.5 on 2023-02-16 05:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TES_new_Model',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('pwd', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'TES_data',
                'db_table': 'TES_data',
            },
        ),
    ]
