# Generated by Django 4.1.5 on 2023-02-28 07:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TES_otp_model',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('otp', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'OTP',
                'db_table': 'OTP',
            },
        ),
    ]
