# Generated by Django 4.1.5 on 2023-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0002_tes_otp_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tes_otp_model',
            name='createdAt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
