# Generated by Django 4.1.5 on 2023-03-01 09:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0003_tes_otp_model_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TES_file_upload_model',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'uploads',
                'db_table': 'uploads',
            },
        ),
    ]
