# Generated by Django 4.1.5 on 2023-03-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0006_tes_submit_new_house_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tes_submit_new_house_model',
            old_name='id',
            new_name='_id',
        ),
    ]
