# Generated by Django 4.1.5 on 2023-03-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0007_rename_id_tes_submit_new_house_model__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tes_submit_new_house_model',
            name='customer_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
