# Generated by Django 4.1.5 on 2023-03-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0008_tes_submit_new_house_model_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tes_submit_new_house_model',
            old_name='_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='tes_submit_new_house_model',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='tes_submit_new_house_model',
            name='email',
        ),
        migrations.AddField(
            model_name='tes_submit_new_house_model',
            name='customer_email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tes_submit_new_house_model',
            name='house_id',
            field=models.CharField(max_length=100),
        ),
    ]
