# Generated by Django 4.1.5 on 2023-03-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0010_tes_house_visits_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tes_house_visits_model',
            name='customer_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
