# Generated by Django 4.1.5 on 2023-03-06 12:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0011_tes_house_visits_model_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TES_template_model',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100)),
                ('template_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'templates',
                'db_table': 'templates',
            },
        ),
    ]
