# Generated by Django 4.1.5 on 2023-03-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0012_tes_template_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tes_template_model',
            name='template_id',
        ),
    ]
