# Generated by Django 4.1.5 on 2023-03-13 12:13

import TESappnew.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0015_alter_tes_report_model_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tes_report_model',
            old_name='id',
            new_name='_id',
        ),
        migrations.AddField(
            model_name='tes_house_visits_model',
            name='current_status',
            field=djongo.models.fields.ArrayField(default=[{'_id': None, 'report_name': None, 'template_id': None}], model_container=TESappnew.models.TES_report_model),
            preserve_default=False,
        ),
    ]
