# Generated by Django 4.1.5 on 2023-03-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0016_rename_id_tes_report_model__id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tes_house_visits_model',
            name='current_status',
        ),
    ]
