# Generated by Django 4.1.5 on 2023-03-15 10:27

import TESappnew.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0017_remove_tes_house_visits_model_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TES_report_status_model',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('report_id', models.CharField(default=None, max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'report_status',
                'db_table': 'report_status',
            },
        ),
        migrations.AddField(
            model_name='tes_house_visits_model',
            name='current_status',
            field=djongo.models.fields.ArrayField(default=[{'_id': None, 'report_id': None, 'status': 'pending'}], model_container=TESappnew.models.TES_report_status_model),
        ),
    ]
