# Generated by Django 4.1.5 on 2023-03-17 10:16

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TESappnew', '0018_tes_report_status_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TES_superadmin',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'TES_superadmin',
                'db_table': 'TES_superadmin',
            },
        ),
    ]
